name: Build Linux DEB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest   # 🔥 Linux machine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm install
        working-directory: agent

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot dpkg

      - name: Build Linux (.deb)
        run: npx electron-builder --linux deb --publish=never
        working-directory: agent

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: agent/dist/*.deb